apiVersion: v1
kind: Service
metadata:
    name: coupon-app
    labels:
        app: coupon-app
spec:
    type: NodePort
    ports:
        - port: 8080
          targetPort: 8080
          nodePort: 30124
    selector:
          app: coupon-app
