apiVersion: v1
kind: Service
metadata:
    name: docker-mysql-service
spec:
    type: NodePort
    selector:
        app: docker-mysql
    ports:
        - nodePort: 30123
          port: 3306
          targetPort: 3306