apiVersion: v1
kind: Service
metadata:
    name: product-app
    labels:
        app: product-app
spec:
    type: NodePort
    ports:
        - port: 8081
          targetPort: 8081
          nodePort: 30125
    selector:
          app: product-app
